### ISSUE TITLE
Include pictures of people

### ISSUE THREAD

**Issue by docNord** [Ingenjorsarbete-For-Klimatet/ingenjorsarbete-for-klimatet.github.io#10]
One of the important points raised in an earlier discussion [here](https://github.com/Ingenjorsarbete-For-Klimatet/ifk-meetings/blob/master/m%C3%B6tesanteckningar_2022_11_30.md) was to include pictures of people in our articles and social media channels. I think we should arrange to include pictures of ourselves in our articles. If that means setting up a complementory data storage, then we should arrange it.

**Comment by docNord** [comment]
I would like the support of you guys here @mgcth and @strobba . I have the following questions, since pictures have been cleared out (I understand that there is a style ideal about generating everything from code, but I would like to discuss the matter still):

- Do you agree that we would improve our credibility by including some pictures of people and events?
- How would you prefer that is done? A static storage space somewhere else, I suppose?

**Comment by mgcth** [comment]
Agree, we should have pictures. I have a free S3 like storage we can use in the meantime, untill we get a VPS/storage or something like that. I'll look into if it is possible to have shared login details for it so all can upload stuff to it.

**Comment by strobba** [comment]
Or we can create a subdomain on our webhotel. We can even create an CDN for css and stuff I guess.

**Comment by mgcth** [comment]
If I could only login :)

**Comment by docNord** [comment]
I would argue this has now been solved - web page has been updated with a lot of pictures and we are no longer an anonymous collective. Good work! Closing,
