### ISSUE TITLE
Remove CNAME

### ISSUE THREAD

**Issue by mgcth** [Ingenjorsarbete-For-Klimatet/ingenjorsarbete-for-klimatet.github.io#34]
**Description**

GitHub Pages docs https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain-and-the-www-subdomain-variant says we don't need a CNAME file (we are not publishing from a branch but an action/workflow). Don't know if that is causing any issues. @strobba

**Comment by strobba** [comment]
I read that also, but something we need to do. I thought the way to go was to change the domain under settings -> pages. According to some guides it should be possible, but I don’t find that setting.

**Comment by strobba** [comment]
How did you do for your webpage?

**Comment by strobba** [comment]
I just tried with a cname because I did not find any other way…

**Comment by strobba** [comment]
I also tried to do a redirection in cpanel but it was not accepted. Maybe there is another redirection that needs to be removed.
