### ISSUE TITLE
Om and Intervjuer

### ISSUE THREAD

**Issue by mgcth** [Ingenjorsarbete-For-Klimatet/ingenjorsarbete-for-klimatet.github.io#40]
**Description**

I see that our member interviews are tagged as _Intervjuer_

https://github.com/Ingenjorsarbete-For-Klimatet/ingenjorsarbete-for-klimatet.github.io/blob/6b6290731340119024ec36c1cd043378ca075352/content/posts/intervju-anders-nord.md?plain=1#L4

but I filtered on _Om_

https://github.com/Ingenjorsarbete-For-Klimatet/ingenjorsarbete-for-klimatet.github.io/blob/20f994a4ea719b7aaaf6820c89bcf3feb3790ca2/theme/templates/page.html#L26

We need to align them. Which do you want to change @docNord, the template or the post?

**Comment by docNord** [comment]
Can just as well change the post.

**Comment by mgcth** [comment]
Closed in #41.
