### ISSUE TITLE
New article highlighting release 0.1.1 of ifk-smhi

### ISSUE THREAD

**Issue by docNord** [Ingenjorsarbete-For-Klimatet/ingenjorsarbete-for-klimatet.github.io#49]
Write article for the web page about the latest developments of `ifk-smhi` and how it is now released and easily installable through pip.

Link to https://mladen.gibanica.net/posts/ifk-smhi and use the examples given there.

- [ ] Write article
- [ ] Mesan example
- [ ] Metfcts example
- [ ] Metobs example
- [ ] Strang example
- [ ] Link to @mgcth personal site

**Comment by mgcth** [comment]
I'd probably include a Mesan or Metfcts example too.
