### ISSUE TITLE
Book new AW

### ISSUE THREAD

**Issue by docNord** [Ingenjorsarbete-For-Klimatet/ingenjorsarbete-for-klimatet.github.io#55]
We need to book a new AW and highlight it in the "events" section. We should also follow it up with pictures and a descriptive article afterwards. 

I propose Thursday 6/4 -23, at Pustervik. If the weather permits, we could enjoy spring sun and a beer in their outdoor serving area while discussing upcoming climate activities.

**Comment by mgcth** [comment]
Good idea, I'll see if that works for me.

**Comment by mgcth** [comment]
I can this Thursday, but maybe two isn't an AW.

**Comment by docNord** [comment]
We could still hang out and discuss some ideas or something - maybe we could get some more people to join. I am participating in that workshop tomorrow, could be interesting to discuss further. Perhaps @strobba could join as well, and maybe some of the others? Let's set it up :)

**Comment by mgcth** [comment]
Yeah, all sounds good to me!
