### ISSUE TITLE
Assets no longer reachable from home page

### ISSUE THREAD

**Issue by docNord** [Ingenjorsarbete-For-Klimatet/ingenjorsarbete-for-klimatet.github.io#73]
I tried finding the presentation material from CeCAR today, but got a 404.
https://ingenjorsarbeteforklimatet.se/assets/files/AW_Volvo_2020107.pptx

**Comment by mgcth** [comment]
That url looks like it is from the old page. @strobba do you have the presentation. I can upload it to our file storage in that case. @docNord, any other presentation material the is missing?

**Comment by docNord** [comment]
https://ingenjorsarbeteforklimatet.se/assets/files/Ingenj%C3%B6rsarbete_f%C3%B6r_klimatet_220316.pdf

https://ingenjorsarbeteforklimatet.se/assets/files/Charlotta_S%C3%B6derberg_IFK_2020.pptx

These two are also missing. The rest of the links seem to work. Thanks!

**Comment by strobba** [comment]
Files sent to Mladen's gmail.
