### ISSUE TITLE
change info mail to anders.

### ISSUE THREAD

**Issue by strobba** [Ingenjorsarbete-For-Klimatet/ingenjorsarbete-for-klimatet.github.io#74]
Since I never read info@ifk.se. I suggest this is changed to Anders Nord's mail.

**Comment by docNord** [comment]
...couldn't we just pass the torch to someone else?

**Comment by mgcth** [comment]
I say we keep it but forward to all our emails, perhaps?

**Comment by docNord** [comment]
Solved by forwarding all emails sent to info@ingenjorsarbeteforklimatet.se to the three members active in this issue, i.e. @strobba @mgcth and @docNord
